
#######################################
# Custom Filament Management Menu
#######################################

[menu __main filament]
name: Filament
icon: filament

[menu __main filament load_pla]
name: Load PLA (210°C)
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_PLA"}

[menu __main filament load_petg]
name: Load PETG (240°C)
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_PETG"}

[menu __main filament load_abs]
name: Load ABS (250°C)
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_ABS"}

[menu __main filament load_tpu]
name: Load TPU (220°C)
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_TPU"}

[menu __main filament load_nylon]
name: Load Nylon (250°C)
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_NYLON"}

[menu __main filament load_custom]
name: Load Custom Temp
icon: arrow-down
method: printer.gcode.script
params: {"script":"LOAD_FILAMENT"}
enable: {{ printer.idle_timeout.state != "Printing" }}

[menu __main filament unload_pla]
name: Unload PLA (210°C)
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_PLA"}

[menu __main filament unload_petg]
name: Unload PETG (240°C)
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_PETG"}

[menu __main filament unload_abs]
name: Unload ABS (250°C)
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_ABS"}

[menu __main filament unload_tpu]
name: Unload TPU (220°C)
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_TPU"}

[menu __main filament unload_nylon]
name: Unload Nylon (250°C)
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_NYLON"}

[menu __main filament unload_custom]
name: Unload Custom Temp
icon: arrow-up
method: printer.gcode.script
params: {"script":"UNLOAD_FILAMENT"}
enable: {{ printer.idle_timeout.state != "Printing" }}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [graph Printer]
#~# heater_bed = False
#~#
